remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

description: |+
  ## LATEST NEWS<br/>
  ________________________________________<br/>
  * Served as a 2024 reviewer for Engineering Applications of Artificial Intelligence, Elsevier, IF: 8.0<br/>
  * Joined a MOHE-FRGS 2024 grant worth 83.7k as a co-PI: Tourism Destination Modeling and Simulation Using AR/VR Technology with Point Cloud and 3D Modeling Techniques<br/>
  * Served as a 2024 reviewer for Computers and Electronics in Agriculture, Elsevier, IF: 8.3<br/>
  * Served as a 2024 reviewer for Int. Journal of Systematic Innovation, CiteScore 2023: 0.8<br/>
  * In 2024, served as TPC for: WPRDM2024, Wuhan (wprdm.com/index.html), DATA'24 (icdabi.uob.edu.bh/), and ICNGN2024, Bangkok (icngn.org/index.html)<br/>
  * Served as a 2024 reviewer for Int. Journal of Human-Computer Interaction, Taylor & Francis, IF: 4.7<br/>
  * Serves as a co-consultant for a SMA-UHSB "Development of Software Sizing Guideline for Sarawak Government" project, commencing Jan 15th, 2024<br/>
  * Served as a 2023 reviewer for Int. Journal of Systematic Innovation, CiteScore 2022: 0.6<br/>
  * Joined a UNIMAS-PILOT 2023 grant worth 20k as a co-PI<br/>
  * Invited speaker at Seminar Kursi PUSAKA 2023<br/>
  * Reviewer for 3ICT2023, Bahrain (iiict.uob.edu.bh/3ict23/)<br/>
  * Completed a UNIMAS-CDRG grant: Automated Skill Determination from Egocentric Video, in May 2023<br/>
  * Appointed as a Research fellow at iTRI & iCREATE, UNIMAS<br/>
  * Served as a 2023 reviewer for Engineering Applications of Artificial Intelligence, Elsevier, IF: 8.0<br/>
  * Served as a 2023 reviewer for Social Sciences & Humanities Open, Elsevier, CiteScore 2023: 4.2<br/>
  * Joined a 2022's matching grant under Konsortium Komputeran & Informatik Borneo as a co-PI w/ a value of 20k<br/>
  * Joined two UNIMAS VC-HIRG 2022 grants as a co-PI w/ an accumulated value of 142k<br/>
  * Joined a MOHE-FRGS 2022 grant worth 95k as a co-PI: An Efficient Deep Transfer Learning Strategy for Accurate Masked Face Recognition<br/>
  * Served as a 2022 reviewer for Int. Journal of Computing and Digital Systems, CiteScore 2022: 1.7<br/>
  * Served as a 2021 reviewer for Journal of Telecommunications and Information Technology, CiteScore 2021: 1.5<br/>
  * Joined two UNIMAS-PARTNERS 2021 grants as a co-PI w/ an accumulated value of 40k<br/>
  * Secured a MOHE-FRGS 2021 grant worth 135k: Design of A Deep Learning Model with Attention Mechanism for Biometric Re-identification of Green Sea Turtles in A Long-term Tracking Scenario<br/>
  * TPC for 2020 5th Int. Conference on Renewable Energy and Environmental Protection, Shenzen<br/>
  * Joined a 2019 research grant on AR/VR solutions for heritage sites, worth 100k from SMA<br/>
  * Joined a 2019 research grant on digital tourism, worth 1.6m from SMA<br/>
  * TPC for ISCIPT2019, Guangzhou (keoaeic.org/ISCIPT2019)<br/>
  * Completed two research grants during the period of Sept - Dec 2018: UNIMAS-SGS (Passive Biometric Identification of Sea Turtles) and MOHE-RACE (Background Subtraction in Egocentric Videos Depicting ADL)<br/>
  * Won a gold medal for MO-LEARN at SIIDEx2018 (Open Category)<br/>
