remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

google_analytics: G-EK0VPEN8RR

description: |+
  * Joined UNIMAS-PARTNERS 2021 grant as a co-PI (Rhizomorph Mycelium Recognition using Deep Learning during Mushroom Cultivation Process) worth 20k MYR<br/>
  * Joined UNIMAS-PARTNERS 2021 grant as a co-PI (Clinically Applicable Machine Learning Model for Classification of COVID-19 Abnormalities Using Chest Radiographs) worth 20k MYR<br/>
  * Secured a MOHE-FRGS 2021 grant worth 135k MYR: Design of A Deep Learning Model with Attention Mechanism for Biometric Re-identification of Green Sea Turtles in A Long-term Tracking Scenario.<br/>
  * A student paper titled “Classification of Digital Chess Pieces and Board Position using SIFT" has been accepted for oral presentation at IEEE ICSIPA 2021.<br/>
  * Technical Commitee Member for The 5th Int. Conference on Renewable Energy & Environmental Protection 2020. All papers published in IOP Conf. Series: Earth and Environmental Science 621(1).<br/>
  * Secured a UNIMAS-CDRG 2019 grant worth 29k MYR: Automated Skill Determination from Egocentric Video<br/>
  * Joined a (2019) 3-year research grant (on AR/VR solutions for heritage sites) worth 100k MYR from SMA.<br/>
  * Joined a (2019) 4-year research grant (on digital tourism) worth 1.6m MYR from SMA.<br/>
  * Completed two research grants during the period of Sept - Dec 2018: UNIMAS-SGS (Passive Biometric Identification of Sea Turtles (Chelonia Mydas)) and MOHE-RACE (Background Subtraction in Egocentric Videos Depicting ADL).<br/>
  * Won a gold medal for MO-LEARN at SIIDEX2018 (Open Category)<br/>
