remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

description: |+
  ## LATEST NEWS<br/>
  ________________________________________<br/>
  * Reviewer for ICNGN2024, Bangkok, Thailand (https://icngn.org/index.html).<br/>
  * Served as a 2024 reviewer for International Journal of Human-Computer Interaction (IJHCI), Taylor & Francis, IF: 4.7<br/>
  * Serves as a co-consultant for a Sarawak Multimedia Authority-UHSB "Development of Software Sizing Guideline for Sarawak Government" project, commencing Jan 15th, 2024.<br/>
  * Served as a 2023 reviewer for Int. Journal of Systematic Innovation (IJoSI), CiteScore 2022: 0.6<br/>
  * Joined a UNIMAS PILOT 2023 grant worth 20k MYR as a co-PI: Enhancing Convolutional Neural Network with Adaptability in Dynamic Changes for Brainprint Authentication Modelling<br/>
  * Invited speaker at Seminar Kursi PUSAKA 2023 (23 - 24 Aug 2023), Raia Hotel & Convention Centre Kuching. Will be sharing our work progress on Agarwood resin segmentation using Deep Learning<br/>
  * Reviewer for 3ICT2023, Bahrain (http://iiict.uob.edu.bh/3ict23/).<br/>
  * Completed UNIMAS-CDRG grant (29k MYR): Automated Skill Determination from Egocentric Video, in May 2023<br/>
  * Joined Institute for Tourism Research and Innovation and Institute of Creative Arts and Technology, UNIMAS, as a Research Fellow<br/>
  * Served as a 2023 reviewer for Engineering Applications of Artificial Intelligence, Elsevier, IF: 8.0<br/>
  * Served as a 2023 reviewer for Social Sciences & Humanities Open, Elsevier Ltd., ISSN: 2590-2911<br/>
  * Joined a 2022's matching grant under Konsortium Komputeran & Informatik Borneo (KKIB) as a co-PI w/ a value of 20k MYR<br/>
  * Joined two UNIMAS VC-HIRG 2022 grants as a co-PI w/ an accumulated value of 142k MYR<br/>
  * Joined a MOHE-FRGS 2022 grant worth 95k MYR as a co-PI: An Efficient Deep Transfer Learning Strategy for Accurate Masked Face Recognition<br/>
  * Served as a 2022 reviewer for Int. Journal of Computing and Digital Systems, CiteScore 2022: 1.7<br/>
  * Served as a 2021 reviewer for Journal of Telecommunications and Information Technology, CiteScore 2021: 1.5<br/>
  * Joined two UNIMAS-PARTNERS 2021 grants as a co-PI w/ an accumulated value of 40k MYR<br/>
  * Secured a MOHE-FRGS 2021 grant worth 135k MYR: Design of A Deep Learning Model with Attention Mechanism for Biometric Re-identification of Green Sea Turtles in A Long-term Tracking Scenario.<br/>
  * Joined a (2019) 3-year research grant (on AR/VR solutions for heritage sites) worth 100k MYR from SMA.<br/>
  * Joined a (2019) 4-year research grant (on digital tourism) worth 1.6m MYR from SMA.<br/>
  * TPC for ISCIPT2019, Guangzhou, China (https://www.keoaeic.org/ISCIPT2019).<br/>
  * Completed two research grants during the period of Sept - Dec 2018: UNIMAS-SGS (Passive Biometric Identification of Sea Turtles) and MOHE-RACE (Background Subtraction in Egocentric Videos Depicting ADL).<br/>
  * Won a gold medal for MO-LEARN at SIIDEX2018 (Open Category)<br/>
