theme: jekyll-theme-minimal
description: |+
            Secured a Cross-Disciplinary Research Grant worth 29,600 MYR: Automated Skill Determination from Egocentric Video Containing Gaze Data. One MSc position <a href="https://www.facebook.com/photo.php?fbid=358465948413829&set=a.221821052078320&type=3&theater">available</a>.
