remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

google_analytics: G-EK0VPEN8RR

description: |+
  * Served as a reviewer for IJCDS (e-ISSN 2210-142X, DOI: dx.doi.org/10.12785/ijcds)<br/>
  * Joined two UNIMAS-PARTNERS 2021 grants as a co-PI w/ an accumulated value of 40k MYR<br/>
  * Secured a MOHE-FRGS 2021 grant worth 135k MYR: Design of A Deep Learning Model with Attention Mechanism for Biometric Re-identification of Green Sea Turtles in A Long-term Tracking Scenario.<br/>
  * Secured a UNIMAS-CDRG 2019 grant worth 29k MYR: Automated Skill Determination from Egocentric Video<br/>
  * Joined a (2019) 3-year research grant (on AR/VR solutions for heritage sites) worth 100k MYR from SMA.<br/>
  * Joined a (2019) 4-year research grant (on digital tourism) worth 1.6m MYR from SMA.<br/>
  * Completed two research grants during the period of Sept - Dec 2018: UNIMAS-SGS (Passive Biometric Identification of Sea Turtles (Chelonia Mydas)) and MOHE-RACE (Background Subtraction in Egocentric Videos Depicting ADL).<br/>
  * Won a gold medal for MO-LEARN at SIIDEX2018 (Open Category)<br/>
