theme: jekyll-theme-minimal
description: |+
  ### Latest News<br/>
  * Secured a UNIMAS-CDRG Grant worth 29,600 MYR: Automated Skill Determination from Egocentric Video Containing Gaze Data<br/>
  * Joined a 3-year research grant (on AR/VR solutions for heritage sites) worth 100,000 MYR from Sarawak Multimedia Authority.<br/>
  * Joined a 4-year research grant (on digital tourism) worth 1.6 million MYR from Sarawak Multimedia Authority.<br/>
  * Won a bronze medal for MO-WALL at MTE2019, http://mte.org.my/<br/>
  * Completed two research grants during the period of Sept - Dec 2018: UNIMAS-SGS (_Passive Biometric Identification of Sea Turtles (Chelonia Mydas)_) and MOHE-RACE (_Background Subtraction in Egocentric Videos Depicting Activities of Daily Living_).<br/>
  * Our initial work on biometric identification of sea turtles was published in JICTRA, 12(3), 256-266, <a href="http://journals.itb.ac.id/index.php/jictra/issue/view/783">doi:10.5614/itbj.ict.res.appl.2018.12.3.4</a>. <a href="https://ir.unimas.my/22902/">[Dataset]</a>, <a href="https://www.dropbox.com/s/z1j5vedueikawjb/TURTLES.zip">[Code]</a>.<br/>
  * Won a gold medal for MO-LEARN at SIIDEX2018 (Open Category), https://www.newsarawaktribune.com.my/news/siidex-draws-707-participants/<br/>
