theme: jekyll-theme-minimal
description: |+
  * Technical Commitee Member for 2020 5th International Conference on Renewable Energy and Environmental Protection. All papers published in IOP Conf. Series: Earth and Environmental Science 621(1).
  * Secured a UNIMAS-CDRG Grant worth 29,600 MYR: Automated Skill Determination from Egocentric Video<br/>
  * Joined a 3-year research grant (on AR/VR solutions for heritage sites) worth 100,000 MYR from Sarawak Multimedia Authority.<br/>
  * Joined a 4-year research grant (on digital tourism) worth 1.6 million MYR from Sarawak Multimedia Authority.<br/>
  * Completed two research grants during the period of Sept - Dec 2018: UNIMAS-SGS (Passive Biometric Identification of Sea Turtles (Chelonia Mydas)) and MOHE-RACE (Background Subtraction in Egocentric Videos Depicting Activities of Daily Living).<br/>
  * Our initial work on biometric identification of sea turtles was published in JICTRA, 12(3), 256-266, <a href="http://journals.itb.ac.id/index.php/jictra/issue/view/783">doi:10.5614/itbj.ict.res.appl.2018.12.3.4</a>.<br/>
  * Won a gold medal for MO-LEARN at SIIDEX2018 (Open Category)<br/>
